---
- name: Configure Ollama
  ansible.builtin.import_tasks: ollama.yml
  
- name: Manage Ollama models
  ansible.builtin.import_tasks: ollama_models.yml

- name: Configure Caddy
  ansible.builtin.import_tasks: caddy.yml
